### ISSUE TITLE
Partition chart mixes up results

### ISSUE THREAD

**Issue by jeremy-ecoenergy** [apache/superset#10586]
I've set up a partition chart with multiple levels of groupings:

shop -> sales owner -> sale/goal

![Screenshot 2020-08-11 at 4 29 13 PM](https://user-images.githubusercontent.com/65153090/89997457-996d1980-dca5-11ea-8017-6c19d53287cb.png)

Superset is not rendering this data correctly, despite the raw results being accurate.

![Screenshot 2020-08-12 at 2 09 09 PM](https://user-images.githubusercontent.com/65153090/89997509-a7229f00-dca5-11ea-84c5-0d8ee1cad251.png)

### Expected results

A partition chart with the following:

Karachi | Wali Mukhtar | Goal (some number)
              | Adnan Shamim | Goal (some number)
              | Jeremy Higgs | Sale (some mumber)

### Actual results

Instead, entries from other sale owners are getting mixed in.

![Screenshot 2020-08-12 at 2 07 37 PM](https://user-images.githubusercontent.com/65153090/89997684-e18c3c00-dca5-11ea-91e0-a131635c79e2.png)

#### Screenshots

Added inline.

#### How to reproduce the bug

Config given above.

### Environment

Running on Preset.

**Comment by JunlinC** [comment]
🏷 chart

**Comment by McHollands** [comment]
I was able to fix this by reverting the changes to PartitionViz.nest_viz made in this MR https://github.com/apache/incubator-superset/pull/9943. Changing the dims from a tuple to a list means it isn't getting concatenated and so when evaluating partiiton charts with greater than 2 levels it breaks

**Comment by guang** [comment]
rip partition charts

**Comment by etr2460** [comment]
Looks like this was fixed, so i'm going to close it

**Comment by guang** [comment]
@etr2460 where are you seeing the fix? i just upgraded to 1.1.0 and still see the same bug (the image im using is here https://hub.docker.com/r/amancevice/superset/)

**Comment by mengdaxing** [comment]
This Bug is still on. When the group num is larger than 2, then the last partition group will be wrong.

**Comment by bluestarfish-t1d** [comment]
This issue is still occurring. Has there been any movement regarding a fix?

**Comment by matiere57** [comment]
reopen issue, svp

**Comment by alpika19186** [comment]
Can you please reopen this issue? Still having this problem for 3 levels! Thank you! :)

**Comment by WulfH** [comment]
@etr2460 Can you please reopen this issue? The problem still exists and makes the partition graph useless for GROUP BYs > 2.

**Comment by qoega** [comment]
My guess issue is here:
https://github.com/apache/superset/blob/f2523b26fa140febe838624ae8508136d01d1389/superset-frontend/plugins/legacy-plugin-chart-partition/src/Partition.js#L202C15-L207

It sorts globally based on weight, but it should sort only within previous group. Some fix like taking weight as a tuple of all weights from root to current node should be enough. But I need to find out how to setup and debug superset locally.

**Comment by rusackas** [comment]
Is this still an issue in 3.x and is anyone willing to take it on? It's at risk of being closed as stale again :)

**Comment by rusackas** [comment]
The screenshots on this issue is ancient, and it seems to have gone stale again. If people are still facing this, I would warmly welcome a new issue to regroup with current screenshots/repo steps/context.
