### ISSUE TITLE
Timestamp is not parsed properly in Charts

### ISSUE THREAD

**Issue by pabrahamusa** [apache/superset#11745]
While creating the Charts the timestamp queries are not parsed correctly. I tried to add table chart and the query as per the logs is 

 SELECT COUNT(*) AS "count"
FROM "default"."mydata"
WHERE "timemillis" >= '2020-11-12 00:00:00.000000'
  AND "timemillis" < '2020-11-19 00:00:00.000000'
ORDER BY "count" DESC

Which fails even if I try in SQLlab because I assume we cannot compare date as varchar. So it could be a potential bug in superset. I see in other tickets this issue is fixed however I am using the latest tag (docker pull apache/incubator-superset:latest) dated 18 Nov 2020 , DIGEST:sha256:92db38930faa65024558242d55e01eb57b5b5359c895aad3da007fcb16520896

![image](https://user-images.githubusercontent.com/47830507/99622397-0e17c880-29f8-11eb-8af0-22176254b929.png)

**Comment by nytai** [comment]
This is likely due to your column not being correctly identified as timestamp by superset. If you open the "edit dataset" modal,  got to the columns tab, is the column Data Type a timestamp type and is Is Temporal checked?

**Comment by pabrahamusa** [comment]
@nytai I can see the timestamp is identified by superset and Temporal checked automatically as well.  I am assuming the superset should cast the varchar '2020-11-12 00:00:00.000000' to timestamp using some date functions.

![image](https://user-images.githubusercontent.com/47830507/99624613-8da79680-29fc-11eb-950d-62b5f48fabe8.png)

**Comment by nytai** [comment]
ah, could it be this? https://stackoverflow.com/questions/38037713/presto-static-date-and-timestamp-in-where-clause

**Comment by pabrahamusa** [comment]
Actually thats what I am doing now, Going to SQLLab and create and test the query with proper date cast and explore -> create charts from there.  Add new Chart option directly will not work.

**Comment by nytai** [comment]
hmm interesting. So is it the explore "Time Range" option that isn't working?

**Comment by nytai** [comment]
@villebro have you seen this before?

**Comment by villebro** [comment]
Thanks for tagging @nytai . @pabrahamusa it seems you're using the `TIME` type, which is fairly poorly supported in Superset. Can you elaborate on your use case, and why this isn't a `TIMESTAMP` or `FLOAT` or similar?

**Comment by pabrahamusa** [comment]
@villebro Actually this is automatically mapped from Pinot schema . In pinot it is LONG , EPOCH timestamp in millis. The pinot presto connector maps it to TIME automatically I presume.  Not sure why it is mapped to TIME rather than TIMESTAMP. https://prestodb.io/docs/current/connector/pinot.html

**Comment by villebro** [comment]
@pabrahamusa oh I didn't realize this was Pinot over Presto. Hmm, not sure how to handle this. Do you think it would be possible to set `pinot.infer-timestamp-type-in-schema` to true? I think Superset is going to have a hard time understanding that the `TIME` type is in fact referring to a Pinot datatype, not the Presto `TIME` one.

**Comment by pabrahamusa** [comment]
@villebro Actually pinot.infer-timestamp-type-in-schema is set to true and presto identifies the column as TIMESTAMP, however the comment section says TIME. I assume we can ignore the comment part. 

presto:default> show columns from pinot.default.mydata;
    ```
 Column     |   Type    | Extra |  Comment
----------------+-----------+-------+-----------
 cluster        | varchar   |       | DIMENSION
 data            | varchar   |       | DIMENSION
 host           | varchar   |       | DIMENSION
 timemillis     | timestamp |       | TIME
```

**Comment by bwgroff** [comment]
I have the same issue with presto, where I see this error:
```
'message': 'line 271:26: Cannot apply operator: timestamp(3) with time zone >= varchar(26)',
```
and here is the offending line of the templated query:
```
WHERE "created_at_month" >= '2014-05-04 00:00:00.000000'
  AND "created_at_month" < '2021-05-04 00:00:00.000000'
```
and confirming that the field is a timestamp:
![image](https://user-images.githubusercontent.com/5002606/117059763-23568a00-acee-11eb-91e8-f4f4cf078e57.png)

Any ideas how I should proceed?

**Comment by villebro** [comment]
@bwgroff What version of Superset are you on? I believe this was resolved quite some time ago, and should no longer be a problem on the current stable release of Superset.

**Comment by bwgroff** [comment]
[v2021.18.0](https://github.com/apache/superset/releases/tag/v2021.18.0) via [this container](https://hub.docker.com/layers/apache/superset/2f9efb2e23cefb8f087e473a10ccb93a90a6311c/images/sha256-c364600b8d5df30afef058b08de93ca8bd4de57592bf9dea80e7441d819af138?context=explore).

**Comment by nytai** [comment]
This appears to be the same issue as https://github.com/apache/superset/issues/807 and it is still an issue on `1.3.2` against a column identified as TIMESTAMP (even though it is DATE in the trino schema). It seems the issue is really with pyhive since it should pre-append the `TIMESTAMP {}` type constructor to timestamp literals.

**Comment by nytai** [comment]
@villebro is there any way we can handle this in superset code? Basically force all date/time literals to be written as `TIMESTAMP <expr>` instead of just `<expr>` for trino

**Comment by nytai** [comment]
Actually it appears this is fixed for the most parts, it's just an issue with DATE columns. Since that issue is being tracked by https://github.com/apache/superset/issues/17143 I'm going to close this issue.
