### ISSUE TITLE
charts colors forced in dashboard do not work anymore ("label_colors")

### ISSUE THREAD

**Issue by squalou** [apache/superset#11826]
See #2524

In a dashbord properties, one can set "label_colors", so that all charts on the dashboard will share the same colors for identical data.

It's been broken in 0.37.2 and 0.38.0. 

Last time seen working was 0.36.0

### Expected results

all charts share the predefined colors of each category, set using "label_colors"

### Actual results

charts original colors arekept, or the one chosen in dashboard is used, but label_colors is ignored

#### Screenshots

When it works :

![image](https://user-images.githubusercontent.com/4623644/100337275-76a60d00-2fd7-11eb-978a-8e15510c0716.png)

With newer version :

![image](https://user-images.githubusercontent.com/4623644/100337499-be2c9900-2fd7-11eb-9055-56fbce12be5a.png)

#### How to reproduce the bug

1. create two bar charts showing categories "category1, category2, ... for instance". Define a different custom palette for each
2. add them on a dashboard
3. go to edit / edit dashboard properties
4. in dashboard properties set for instance 

```
"label_colors": {
    "category1": "rgb(248, 166,28)",
    "category2": "black",
    "category3": "rgb(227, 59, 5)",
    "category4": "rgb(245, 104, 7) ",
    "category5": "rgb(230, 28, 96)",
    "category6": "rgb(0, 228, 201) "
  },
```
5. look at the dashboard : it does never use these "label_colors"

NOTE : in dashboard settings, selecting a palette does overwrite charts palettes, removing a palette tehre leaves the charts one,
but "label_colors" is never used.

### Environment

- superset version: `superset version`

```bash
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Superset 0.38.0
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
```

- python version: `python --version`

```python
- Python 3.6.7
```

node.js version: `node -v`

```js
v12.16.3
```
### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by junlincc** [comment]
related issues [#11677](https://github.com/apache/incubator-superset/issues/11677) [#11674](https://github.com/apache/incubator-superset/issues/11674)

**Comment by squalou** [comment]
I tried. So many refreshes and combinations of actions. Save, save as new, ne charts, remove colors entirely from dashborad properties, etc etc.

a word about  #11674 : in that issue, the consistence in dashboard --> explore chart worflow is disccussed.

In my case I'm more looking for consistency *on a single dashboard* accross different charts. It's slightly different and the solution may be the same in the end. But as a "use case" it's very different, I hope the initial explanation was undertandable :)

The need underneath is : affect *one fixed color* to a category once and for all. (Once per dashboard or even one for all susperset, in my specific case it would be fine)

**Comment by lilila** [comment]
You simply need to set up a default color for your dashboard.

**Comment by squalou** [comment]
Already tried that, or maybe I might not understand really what you mean. Could you elaborate a bit ? I'd be more than happy to make it work.

**Comment by lilila** [comment]
I can ensure you that label_colors work in dashboards for superset 38. 
I have trouble editing dashboard metadata with the menu so I usually go on dashboard list, click on the edit buttom and change the value of `colors_scheme`  as shown on the picture.

 
<img width="923" alt="Screenshot 2020-12-08 at 11 55 03" src="https://user-images.githubusercontent.com/607430/101475089-38500c80-394c-11eb-8969-2a0170bfa0d7.png">

**Comment by squalou** [comment]
That's weird.
I can edit as you do from dashboard list, or even from dashboard edit itself (choosing a colot scheme from deopdown).
It does persist "color_scheme" alright.
But then : these colors are applied to all charts in dashboard.
(It seems funny when I write it because : it's exactly what one would expect I guess when choosing a dashboard color scheme.)

my "label_colors" are ignored.

example of my json (masked names but you'll get the idea). I don't see label_colors in your case, could you expand a bit the view ? maybe I set them in a wrong place (that used to work though)

![image](https://user-images.githubusercontent.com/4623644/101480636-3f7b1880-3954-11eb-9944-f7d41da5e1d7.png)

**Comment by squalou** [comment]
(additional info : there seems to be indeed some cases when it works, then something break it, still investigating to see from scratch at what moment soemthing goes wrong)

**Comment by squalou** [comment]
Finally I've one thing that works, I hope it will help tackle the root issue, which is in the end : one has to guess the right settings and nothing guides the tries and errors :) .

If you have
- charts with "**superset**" color palette chosen  (AND NO OTHER)
- note : any custom 'label_colors' can be defined on the chart itself, not an issue
- dashboard with *any* color palette chose or even `null`
- then add `{"label_colors":{"name":"#123456"}}` to Dashboard json properties 
- don't forget to refresh Dashboard after each label_color change

=> in this case it works

Once upon a time : Charts required ti use Rb&b palette, now it requires superset.

**Comment by nytai** [comment]
@squalou based on your comments it seems this is resolved? Can you please reopen if it's not the case

**Comment by hosswald** [comment]
This is still broken in 1.2.0.
I found, strangely, that
``` 
  "label_colors": {
    "SUCCESS": "#2ca02c",
    "WARNING": "#ff7f0e",
    "ERROR": "#d62728"
  },
  "color_scheme": "SUPERSET_DEFAULT"
```
works, while

``` 
  "color_scheme": "SUPERSET_DEFAULT",
  "label_colors": {
    "SUCCESS": "#2ca02c",
    "WARNING": "#ff7f0e",
    "ERROR": "#d62728"
  }
```
does not, e.g. JSON metadata order matters (which does not make any sense).

_Originally posted by @hosswald in https://github.com/apache/superset/issues/2524#issuecomment-884062374_
