### ISSUE TITLE
[Explore] Metric/Filter Popover should always corresponds to the actual metric/filter item

### ISSUE THREAD

**Issue by ktmud** [apache/superset#12364]
#### Screenshots

![drag-drop](https://user-images.githubusercontent.com/335541/104071967-0a661e00-51bf-11eb-979e-1231878a3015.gif)

#### How to reproduce the bug

1. Add at least two metrics
2. Click to open the popover of the second metric
3. Drag & Drop to change order or delete the first one
4. Save the popover. 
5. It should have updated the original metric but it updates the other metric at the original position instead.
6. Then if change the other metric, both metrics are updated.

### Environment

Latest master

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by ktmud** [comment]
@junlincc I don't think this is a cosmetic issue. It's a functionally incorrect behavior.

**Comment by junlincc** [comment]
Sounds right.major refactoring work for control fields is gonna happen soon.We will address all related known issue together. But feel free to add p1 label if you consider this particular one as 1.0 release blocker @ktmud

**Comment by junlincc** [comment]
This behavior only happens when you have two same metrics. which means... it has been resolved by https://github.com/apache/superset/pull/12657

**Comment by ktmud** [comment]
https://user-images.githubusercontent.com/335541/105816164-ce75db80-5f68-11eb-819c-c1fa9d1b4618.mp4

This bug is still reproducible.

**Comment by ktmud** [comment]
Another symptom of the same indexing/selected item IDing issue: if you delete one of the metric/adhoc filter, the popover messes up for all other items after the deleted one.


https://user-images.githubusercontent.com/335541/114465478-079f0e80-9b9c-11eb-9c1c-a730f961f2ac.mp4

**Comment by geido** [comment]
I'll have a look at this

**Comment by geido** [comment]
@kgabryje would you mind getting this under your wing? It looks like you have worked on this functionality heavily and you should have more context than I do. I am struggling to find the root cause.
