### ISSUE TITLE
Chart Export CSV output is blank

### ISSUE THREAD

**Issue by rvabhijith** [apache/superset#13373]
Export CSV option in charts handled by the new /chart/data api returns a blank csv file 

Dataset : Virtual dataset
Using Jinja template in query for getting filter values

Reason identified : filter values passed in the json payload (form_data) is not getting applied in the actual query executed.
Query getting executed with blank values hence no result

**Comment by rvabhijith** [comment]
This issue is happening only when there are incompatible filters (warning displayed in the dashboard). In my virtual dataset query, i have not selected the columns in which the dashboard filters are getting applied instead i have selected only the columns i need. Using jinja templates directly in the where condition the results are getting filtered as expected. I hope there is nothing wrong with this method.

Closing this issue since i was able to export csv when i select the same columns also in the dataset query in which the filters are getting applied.

**Comment by mohansaimandalapu** [comment]
Hi rvabhijith 

I am interested in solving this issue, this is my first OSP, can you help me in to solve this issue

**Comment by youngsol** [comment]
@rvabhijith  is this still available?

**Comment by nijcapur** [comment]
Any update on this issue, We are facing the same issue in version 1.1.0, is this resolved in any of the latest versions? need it on urgency.

**Comment by nijcapur** [comment]
I tried on latest version as well at local, it seems working fine as well, the issue was when i used the {{currentUserName()}} or {{url_param('xyz')}} it doesn't download. Need to verify the same in dev env. as well though.

**Comment by Ashish7129** [comment]
@[rvabhijith](https://github.com/rvabhijith) @junlincc @betodealmeida @[mohansaimandalapu](https://github.com/mohansaimandalapu) We are using superset version 1.2 and the issue is still there. By any chance, Is this Issue resolved? If Yes, Please share the PRs/Superset Version link?

**Comment by chase-lewis-akasa** [comment]
I'm experiencing this issue also. This appears to be related to {{url_param('stuff')}} not being passed through on the export csv option.

If I View Chart In Explore -> Run in SQL Lab -> then download CSV this works. However it won't work when downloaded from an embedded vieew or when seeing it in Explore if it uses url_params.

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please open a new Issue or a PR to address the problem.  Or we can re-open this. If anyone still wants to open a PR to fix something here, please do! :D
