### ISSUE TITLE
[explore]server pagination is not working before saving the chart

### ISSUE THREAD

**Issue by junlincc** [apache/superset#14727]
server pagination is not working, the regular pagination is working properly. 

https://user-images.githubusercontent.com/67837651/118917382-9f072800-b8e5-11eb-850f-c94a2491a4a6.mov

@jinghua-qa thanks for spotting!

**Comment by junlincc** [comment]
only happen before saving the chart. known issue, we are looking into a fix. 
https://user-images.githubusercontent.com/67837651/118930961-46428a00-b8fb-11eb-99b0-8cd8e5fb2308.mov

**Comment by villebro** [comment]
This was fixed by #14779

**Comment by Veonms** [comment]
Hi @junlincc. I see that this issue has been fixed with #14779, but I am still experiencing the same issue as you did, as shown in your first screen recording. I can’t seem to find any changes made to the pagination between the fix and now, so wondering if this issue is still prevalent. I tried this on the out-the-box superset and I still have the same results. Any insights are appreciated.

**Comment by hosswald** [comment]
@villebro it's still not working in 1.3.0. Page buttons remain disfunctional until the chart is saved.

**Comment by villebro** [comment]
That's weird, I distinctly remember this working when reviewing #14779. @simcha90, if you have any spare bandwidth, would you be able to check if this works for you?
