### ISSUE TITLE
The filter mapping settings are not valid

### ISSUE THREAD

**Issue by jianxia84** [apache/superset#15736]
The filter mapping settings are not valid

### Expected results

Configure filter scopes will take effect after saving

### Actual results

Configure filter scopes, unable to save effectively

#### Screenshots

![image](https://user-images.githubusercontent.com/28744116/125926179-7b5eb46c-88e2-410d-af7f-210eac92a7b3.png)

cacel first  scope  and save
![image](https://user-images.githubusercontent.com/28744116/125926218-96532e32-3b6f-4044-8aab-c3fbe85620fd.png)

save dashboard 
![image](https://user-images.githubusercontent.com/28744116/125926336-da7fa42d-22ef-4f45-9346-0eeb60c440d7.png)

refresh url，the setting is not saved 
![image](https://user-images.githubusercontent.com/28744116/125926470-2ec188f2-34bc-4b8e-a654-9ece57c5acf5.png)

#### How to reproduce the bug

1. Set configure filter scopes and cancel one filter scopes

2. Refresh after saving

3. Configure filter scopes is still in the original state and has not been saved

### Environment

(please complete the following information):

- superset version: 1.2.0
- python version: 3.6.8
- node.js version: 12.18.3

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ * ] I have reproduced the issue with at least the latest released version of superset.
- [ * ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by junlincc** [comment]
Try latest master, should have been fixed. LMK. 🙏 @jianxia84

**Comment by PowerPlop** [comment]
I still experience this bug in v1.3.1 when the feature flag cross filters is enabled.

**Comment by amitmiran137** [comment]
Can you check again on the 1.4.0 release?
a lot of issue have been addressed

**Comment by srinify** [comment]
Closing for now since we believe this has been fixed. Please re-open with new reproduction instructions (ideally using sample dashboards / datasets) if it hasn't been fixed @PowerPlop @jianxia84
