### ISSUE TITLE
[pivot 2] unnecessary scroll bar when chart is added to dashboard 

### ISSUE THREAD

**Issue by rosemarie-chiu** [apache/superset#15831]
Unnecessary scroll bar when pivot 2 is added to dashboard

#### Screenshots

![CleanShot 2021-07-21 at 17 27 00@2x](https://user-images.githubusercontent.com/52086618/126575905-cf5ef662-385a-4b8a-971e-a29b6e6d756b.png)

#### How to reproduce the bug
1. Create a pivot 2 chart
2. Add this chart to a dashboard

### Environment
Latest master

**Comment by kgabryje** [comment]
@rosemarie-chiu I cannot reproduce :( 
![image](https://user-images.githubusercontent.com/15073128/126640755-9ace4ef8-1b9f-48ca-8f1d-f60d988ad78f.png)

**Comment by kgabryje** [comment]
Can you test it again on latest master? I merged a PR related to pivot table today

**Comment by rosemarie-chiu** [comment]
@kgabryje hum, I pulled latest master and I still see it. I have native filter, x-filtering, d&d feature flags enabled. Maybe try that?

**Comment by junlincc** [comment]
it happened with all the latest FFs are on. @kgabryje

**Comment by kgabryje** [comment]
No luck. I enabled drag and drop, cross filtering and native filters, I tested on different window sizes and resolutions and I don't see a scroll bar....
