### ISSUE TITLE
SQL editor not opening

### ISSUE THREAD

**Issue by akshay26031996** [apache/superset#16960]
When I am trying to open [sqllab](http://localhost:8088/superset/sqllab/), it is not showing the area for query editor. After I select the table from the left pane `See Table Schema`, the page becomes empty. Attaching the screenshot of both.

The following error appears in console after selecting the table. There is no error before that.
```
TypeError: Cannot read properties of undefined (reading 'running')
    at QueryStateLabel (sqllab.c8f58705d6d6b7dac380.entry.js:23617)
    at oh (vendors.cda20b85fb1433aaddaf.entry.js:55371)
    at Rj (vendors.cda20b85fb1433aaddaf.entry.js:55479)
    at Qj (vendors.cda20b85fb1433aaddaf.entry.js:55464)
    at Kj (vendors.cda20b85fb1433aaddaf.entry.js:55464)
    at yj (vendors.cda20b85fb1433aaddaf.entry.js:55457)
    at vendors.cda20b85fb1433aaddaf.entry.js:55341
    at exports.unstable_runWithPriority (vendors.cda20b85fb1433aaddaf.entry.js:55572)
    at cg (vendors.cda20b85fb1433aaddaf.entry.js:55340)
    at fg (vendors.cda20b85fb1433aaddaf.entry.js:55341)
```
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/10262118/135895785-91432e04-8aa5-4c86-9fb5-5687c04957ab.png">

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/10262118/135894045-ad921af6-c3f7-474e-8d1d-92908ea86a52.png">

#### How to reproduce the bug
1. Add pyhive in docker/requirements-local.txt
2. Run docker-compose -f docker-compose-non-dev.yml up
3. Connect to a database. I have connected with presto.
4. Go to SQL Lab -> SQL Editor

### Expected results
Query editor should show up.

### Environment
* Browser type and version: Tested in both Firefox and Chrome
* Superset version: superset version: Dev

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by etr2460** [comment]
Thanks for reporting, we can repro this (there seems to be an issue with the Webpack 5 upgrade in prod) and are currently working on a fix

**Comment by etr2460** [comment]
This should be resolved in the master branch now

**Comment by markmckenziecan** [comment]
I did "docker-compose down; git pull origin master; docker-compose up" and I'm still seeing the issue.

Which pull request fixed it?

**Comment by markmckenziecan** [comment]
The TypeError I'm seeing is slightly different than above, but the failure mode is the same:

![image](https://user-images.githubusercontent.com/86323899/136071766-843dc9b1-90b0-4ed9-9865-2444ab9e1f9d.png)
