### ISSUE TITLE
While exporting CSV , only the entries on first  page are getting downloaded even when user  is on other pages

### ISSUE THREAD

**Issue by pratikgera123** [apache/superset#17861]
When multiple pages are present in a report and user clicks on export CSV , only the data from first page is getting exported in CSV even when any other page is selected.

#### How to reproduce the bug

1. Open any report
2. Navigate to any other page using pagination
3. Click on export CSV

#### Screenshots
![image](https://user-images.githubusercontent.com/96576388/147241095-d2681661-af93-4f40-9571-d5219aecd05e.png)

### Environment

- browser :Chrome
- superset version: `1.3.1`

**Comment by amitmiran137** [comment]
@villebro could you think of a possible solution for this one ?

**Comment by noobyogi0010** [comment]
Hi @amitmiran137 !
I would like to work on this issue if nobody has already taken it up.
Thanks.

**Comment by nijcap01** [comment]
Any update on which version can we expect this, also in the above we are using sql templating in datasets.

> Hi @amitmiran137 ! I would like to work on this issue if nobody has already taken it up. Thanks.

**Comment by geido** [comment]
Hello @noobyogi0010 that would be great! Let me know if you are still interested in working on this issue

**Comment by hosswald** [comment]
@noobyogi0010 @geido 
Our customer also has issues with ne combination of server pagination & csv export.
The behaviour is different from exporting from a chart without server pagination.

In a "normal" chart, all pages would be downloaded (e.g. 10 pages a 10 entries = 100 row csv).
In a "server paged" chart, the "export CSV" function will
- download the first page only
- ignore "show <n> entries" (always use the default "server page length"

I would suggest not necessarily going @pratikgera123's proposed way (download the current instead of the first page) but instead harmonizing "server paged" CSV export with normal CSV export, e.g. they should behave the same.

Ideally, the CSV export option should offer a pop-up where such things can be selected before downloading.

**Comment by ankuraga2022** [comment]
While downloading the CSV file irrespective of pagination i.e. 10/20/50 items or "All" items in the list, the downloaded file consists first 20 records. Validated on multiple reports and different datasets.
<img width="81" alt="Pagination" src="https://user-images.githubusercontent.com/99324676/153170672-61603a53-1b77-49de-91e0-e1eed8f924ee.png">

**Comment by ajaysharma202** [comment]
> When multiple pages are present in a report and user clicks on export CSV , only the data from first page is getting exported in CSV even when any other page is selected.
> 
> #### How to reproduce the bug
> 1. Open any report
> 2. Navigate to any other page using pagination
> 3. Click on export CSV
> 
> ### Expected results- Csv file with entries of current page should get downloaded
> ### Actual results- CSV file with entries of first page getting downloaded
> #### Screenshots
> ![image](https://user-images.githubusercontent.com/96576388/147241095-d2681661-af93-4f40-9571-d5219aecd05e.png)
> 
> ### Environment
> * browser :Chrome
> * superset version: `1.3.1`

I am also getting the same issue. 
Can anyone suggest if we can expect this fix in near future?

**Comment by nijcap01** [comment]
Hi Team,

Any update on this item, our client is following us regularly on this, Please let us which version we are targeting this so that we can respond accordingly.

Thanks

**Comment by Narendra678** [comment]
I am also facing saME ISSUE

**Comment by huimingz** [comment]
same issue

**Comment by vicmion** [comment]
I am also having the same issue.

**Comment by LahmerIlyas** [comment]
Hi @geido 
I would like to work on this issue if no one else is working on it. I was able to reproduce it locally and I think that the issue is that related to the attribute row_offset is always sent as 0 in the post request when exporting as csv.

If no one is working on this, I can try resolving it.

**Comment by LahmerIlyas** [comment]
@geido I was able to resolve the issue. Apparetly the ownstate prop was not being passed to `ConnectedExploreChartHeader` and the useExploreAdditionalActionsMenu() hook. I will create a PR for that

**Comment by Narendra678** [comment]
Hi Team,

Thanks for reply.

What do you mean by ownstate? and useExploreAdditionalActionsMenu() hook

Is it resolved? may i know what changes i have make, please let me know.

Regards,
Naren
________________________________

**Comment by LahmerIlyas** [comment]
@Narendra678 it was a bug in the code, and I resolved it and submitted a pull request for it, but no one reviewed it yet.

Here is a video of how it looks:

https://user-images.githubusercontent.com/31275446/170705451-994fb43f-9bef-4ed5-bf7d-592a417c7f0c.mp4

**Comment by LahmerIlyas** [comment]
@geido could you help me getting the [PR](https://github.com/apache/superset/pull/20178) reviewed.

**Comment by MengXinAlex** [comment]
> @Narendra678 it was a bug in the code, and I resolved it and submitted a pull request(https://github.com/apache/superset/pull/20178/files) for it, but no one reviewed it yet.
> 
> Here is a video of how it looks:
> 
>  output.mp4

Hi [LahmerIlyas](https://github.com/LahmerIlyas), thanks for your help! it is solved my issue.

**Comment by mdeshmu** [comment]
In my case, with server pagination enabled, both option behave same way and download only first page.
 Is this PR going to make "Full CSV Export" option download all pages ?

**Comment by mdeshmu** [comment]
@LahmerIlyas How will it behave when i choose "All" entries. 
![image](https://user-images.githubusercontent.com/57723564/172571675-318e3ecd-9a76-4884-90e8-07e716b270f1.png)

**Comment by LahmerIlyas** [comment]
@mdeshmu I tried changing the page size to 50 and it downloaded a 50 rows csv file
![export 50 items](https://user-images.githubusercontent.com/31275446/172598208-58ed59e6-ecdd-408a-b1e3-c28e765b1bc0.png)

**Comment by mdeshmu** [comment]
Please confirm, you are testing with "Export CSV"? 
How does "Export CSV" behave when you choose "All" option? 
How does ""Export Full CSV" behave after your changes?

**Comment by LahmerIlyas** [comment]
@mdeshmu yes, I confirm that I'm using "Export CSV".

**Comment by LahmerIlyas** [comment]
@mdeshmu 
Yes, I confirm that I'm using "Export CSV".
When you choose "All" option, it will download all rows.
For the "Export Full CSV", this PR doesn't implement this feature (I'm okay with contributing such feature if the maintainers are okay with it).

**Comment by mdeshmu** [comment]
@LahmerIlyas 
"Export Full CSV" feature is already there controlled via flag ALLOW_FULL_CSV_EXPORT but it doesn't work as expected. 
My understanding is, it should export full csv irrespective of what page you are on in dashboard or chart's server page length value.

**Comment by nijcap01** [comment]
Any update on this issue, is above PR included in any version?

**Comment by geido** [comment]
Hello. As this issue has been stale for a while now, I'll be closing it. If anyone experiences this issue in a recent version of Superset, please feel free to submit a new one.

**Comment by gstamatakiswxm** [comment]
This is still an issue for me on 3.1.0, when pagination is enabled only the first page is downloaded even if the 'ALLOW_FULL_CSV_EXPORT' flag has been enables.

**Comment by heichong** [comment]
This is still an issue for me on 4.0.1 ...

**Comment by rusackas** [comment]
Thanks for testing... we'll reopen this.

**Comment by vineetdpnd** [comment]
Is this issue going to be resolved in the upcoming release 4.1.0 ?

**Comment by devysh1907** [comment]
@vineetdpnd issue is not resolved in 4.1.1, any updated if in future it will get resolved?

**Comment by RafaelQ31** [comment]
Happening here too, it's a big issue as we need server side pagination and the customer wants to download all the pages in one go.

**Comment by paulobitar** [comment]
Same problema. It works if you desable server side pagination but this has a high cost !

**Comment by rusackas** [comment]
I'm actually finding that when you enable the frontend limit, the server pagination doesn't _seem_ to be working as expected at all. CC @sadpandajoe to see if he has any input / test coverage / context around this that I might not be aware of.

**Comment by sadpandajoe** [comment]
Nope, nothing that I can think of. Probably need someone to look at this since it sounds like it might only happen if you have server side pagination enabled.

**Comment by paulobitar** [comment]
> I'm actually finding that when you enable the frontend limit, the server pagination doesn't _seem_ to be working as expected at all. CC [@sadpandajoe](https://github.com/sadpandajoe) to see if he has any input / test coverage / context around this that I might not be aware of.

I hope you can fix this bug soon, as it is currently a frequent complaint from users and something that has been happening for a long time.

**Comment by rad-pat** [comment]
I think this bug probably was fixed at one point, it seems now though that the `props.ownState` [here](https://github.com/apache/superset/blob/96cb6030c800976fa73772de98df09ffab3a9af4/superset-frontend/src/dashboard/components/gridComponents/Chart.jsx#L370) is no longer returning anything

**Comment by rad-pat** [comment]
@kgabryje, you did some performance improvements in https://github.com/apache/superset/pull/31241 that seem to touch this last, can you perhaps advise where to pick up the `ownState` now? Also other members like `isCached` also seems to be gone.

**Comment by rusackas** [comment]
https://github.com/apache/superset/pull/34259 should resolve this one :)

**Comment by kgabryje** [comment]
@rusackas @rad-pat Actually, it looks like export to csv downloads all data now (limited by row limit), not just the current page and it seems like expected behavior. This behaviour has been introduced 2 months ago in @amaannawab923's PR https://github.com/apache/superset/pull/33357.

<img width="904" height="684" alt="Image" src="https://github.com/user-attachments/assets/0acd46df-bc08-4b11-9666-a0b035860234" />

**Comment by rusackas** [comment]
Awesome... we'll call this one case closed then, but we're happy to revisit/reopen as needed if there are further issues when the code is in an official release.

**Comment by tonytrill** [comment]
Do you guys know what version this is fixed in? The PR #https://github.com/apache/superset/pull/33357 doesn't seem to have made it an any of the latest releases.

**Comment by GSVSoMuchForSubtlety** [comment]
@rusackas We are on version 5.00 + Postgres. This issue still persists. When pagination is on, only the first page is exported via excel/csv. (Even if full export is selected.)

**Comment by pandvan** [comment]
> Do you guys know what version this is fixed in? The PR #[#33357](https://github.com/apache/superset/pull/33357) doesn't seem to have made it an any of the latest releases.

It seems added from version 6.0.0 (currently in RC phase).
