### ISSUE TITLE
Not possible to configure filter scopes in 1.4.1 / existing filter scopes information gets lost when editing Dashboard Properties

### ISSUE THREAD

**Issue by rafalpas** [apache/superset#19026]
When dashboard properties are edited using the Dashboard Properties dialog, the information about filter scopes for filter boxes (added in Superset versions prior to 1.4) is removed from JSON Metadata. As a result all filters are applied for all other filters and all charts. This also blocks adding any filter scopes information to a new dashboard in Superset 1.4.1.

#### How to reproduce the bug

1. Create a dashboard that includes at least one chart and one filter box.
2. Open the Dashboard Properties dialog using the "Edit" action from dashboard's list.
3. Click on "advanced" to show the JSON METADATA
4. Notice the following section in the content: `"filter_scopes": {"175": {"your_filter_name": {"scope": ["ROOT_ID"], "immune": []}}},` . This section normally allows to configure filter scopes, e.g. adding a chart id in the array under "immune" makes this chart immune to that filter.
5. Try to do any change (e.g. add the chart id in the array under "immune"), enter URL SLUG or just click SAVE without any changes
6. Reopen the Dashboard Properties panel and examine the JSON METADATA

### Expected results

The "filter_scopes" section in JSON METADATA is as defined by you when clicking "SAVE"

### Actual results

The "filter_scopes" section is no longer present in JSON METADATA.

#### Screenshots

none added

### Environment

- browser type and version: Microsoft Edge 98.0.1108.62
- superset version: 1.4.1
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active: VERSIONED_EXPORT

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

Just opening Dashboard Properties and clicking SAVE is enough for the "filter_scopes" section to disappear. It is no longer possible to configure filter scopes for new dashboards in 1.4.1. 
It is also not possible to do any changes to dashboard properties for dashboards created in versions prior to 1.4 without losing the filter scopes information.
Problem reproduces with DASHBOARD_NATIVE_FILTERS enabled and disabled.

**Comment by villebro** [comment]
@rafalpas thanks for reporting. Sounds like the scoped chart ids need to be updated similar to how we do for native filters.

**Comment by rafalpas** [comment]
@villebro - I have made a mistake when analyzing the problem. There was one additional step that I made and apparently this step is the root-cause of the problem. The export itself is correct.

It seems that the information about filter_scopes is removed from dashboard's properties whenever it is edited using the Dashboard Properties dialog. The procedure is as follows:

1. Open Dashboard Properties using the 'Edit" action from dashboard's list - do this for a dashboard that has filter boxes with some "filter scopes" defined. The information about filter boxes can be seen in the JSON Metadata "filter_scopes_section", e.g. `
  "filter_scopes": {
    "28": {
      "technology": {"scope": ["ROOT_ID"], "immune": [40]},
      "software_release": {"scope": ["ROOT_ID"], "immune": [40]},
      "on_air": {"scope": ["ROOT_ID"], "immune": [40]}
    },
    "40": {
      "date_str": {"scope": ["ROOT_ID"], "immune": []},
      "entity": {"scope": ["ROOT_ID"], "immune": []},
      "data_source": {"scope": ["ROOT_ID"], "immune": []}
    }
  }`
2. Click the "Save" button (you do not have to do any actual change)
3. Open the Dashboard properties again and check the JSON Metadata section - the "filter_scopes" section is now missing.
The problem reproduces no matter if DASHBOARD_NATIVE_FILTERS is enabled or not.

How should I proceed - should I update the name and description of this report or should I file a new report and this one gets closed?

**Comment by rafalpas** [comment]
@villebro - I have just updated the ticket. The problem with 1.4.1 is actually much bigger than I thought.

In 1.4.1 it is not possible to define filter scopes for legacy filter boxes as it requires editing Dashboard Properties and each such edit removes the respective section from JSON METADATA.
For dashboards created prior to this version (1.3) that have correctly configured filter scopes, it is not possible to edit any dashboard properties (e.g. URL SLUG) as filter scopes will be removed.

**Comment by villebro** [comment]
Ok @rafalpas, we'll try to get this into the forthcoming 1.4.2 release.

**Comment by yueyuc** [comment]
My version is 1.3.2，where is chart id？i can't find them

**Comment by yueyuc** [comment]
> My version is 1.3.2，where is chart id？i can't find them

ohh,I found them through the sqllite file

**Comment by ValentinC-BR** [comment]
Same here...

Here is my environment : 
* Browser type and version: Google Chrome Version 99.0.4844.51 (Oficial build) (x86_64)
* Superset version: 1.4.1
* Python version: 3.8.12
* Node.js version: doesn’t apply, I run on Kubernetes, using gunicorn as server
* Source : AWS Athena
* Any feature flags active: ALERT_REPORTS, ENABLE_TEMPLATE_PROCESSING, DASHBOARD_NATIVE_FILTERS

**Comment by rusackas** [comment]
We're no longer supporting 1.4.x, and we're on 2.0.1 as of this writing. I believe this is resolved, so I'm optimistically closing this, but if anyone sees any vestige of this issue, we can happily re-open this, or open a new Issue with updated context.

**Comment by bendlikeabamboo** [comment]
We are on 2.0.1 and this is still happening. There is a filter_scope in place (mainly for the scoping of the filter_boxes) but upon modification of the dashboard slug, it removes the filter_scope item.

- Browser type and version: Microsoft Edge: Version 115.0.1901.183 (Official build) (64-bit)
- Superset version: 2.0.1
