### ISSUE TITLE
Upload csv to existing clickhouse is not supported

### ISSUE THREAD

**Issue by LuPan2015** [apache/superset#19247]
superset does not support uploading csv to a table that does not exist in clickhouse because clickhouse must specify the engine when creating the table. 
But why doesn't it support upload csv to a table that already exists in clickhouse?

**Comment by zhaoyongjie** [comment]
> 

This is due to the Superset using pandas to upload CSV instead of using an external table(like Hive or other DB). refer to [link](https://github.com/apache/superset/blob/aa5c80bda6856295368c937307bcec75bba957cf/superset/views/database/views.py#L131).

**Comment by LuPan2015** [comment]
Is there a list of DBs that support upload csv now?

**Comment by srinify** [comment]
@LuPan2015 that list doesn't exist unfortunately but I'm hoping the community will create one soon!

**Comment by rusackas** [comment]
@shreesham pining you here since you're both a resident clickhouse SME, and also perhaps capable of helping to build some documentation around database/CSV upload compatibility.

**Comment by rusackas** [comment]
I think this was resolved, so I'll close it. We also have a table of database driver compatibilities... not sure if CSV upload support can easily be made into a new row there (cc @betodealmeida)

**Comment by quangbilly79** [comment]
Any update on this? Need to upload file to Clickhouse through Superset UI.
Clickhouse:

<img width="496" height="503" alt="Image" src="https://github.com/user-attachments/assets/e6c88219-a724-4995-8051-33c294752b70" />

Other db:

<img width="470" height="459" alt="Image" src="https://github.com/user-attachments/assets/992314b4-5512-420e-9fe5-5829a7bee818" />

**Comment by quangbilly79** [comment]
> I think this was resolved, so I'll close it. We also have a table of database driver compatibilities... not sure if CSV upload support can easily be made into a new row there (cc [@betodealmeida](https://github.com/betodealmeida))

This is not resolved. Clickhouse connection still does not support it!
