### ISSUE TITLE
Chart reverts changes after being saved when coming from dashboard

### ISSUE THREAD

**Issue by michellethomas** [apache/superset#20470]
Users have noticed buggy behavior when exploring a chart from dashboard. 

#### How to reproduce the bug

1. Go to a dashboard and click out to explore one of the charts
2. Make a change to the chart and run the chart
3. Click save as to create a new chart and remove the add to dashboard
4. On save chart reverts back to the original chart from dashboard

### Expected results

Chart should display the new saved chart after saving. 

### Actual results

Chart reverts back to the original chart before the changes. The chart has actually changed and saved correctly, so you can find it in the chart list you'll be able to see the correct chart. Also if you go to save it again you'll still see the add to dashboard filled out with the dashboard the chart originally came from (even though your saved version was not added to the dashboard).

### Environment

(please complete the following information):

- browser type and version:
- superset version: [`superset version`](https://github.com/airbnb/superset-fork/tree/v2022.19.2.1) on a branch with changes through May 18 (with some fixes added)
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by Shazad-khan** [comment]
This issue has been fixed can you please check it and close the issue i have checked this issue but it is working as expected

**Comment by fertek** [comment]
I confirm this bug in version 2.1.1.

In version 3.0.1, the correct version of the chart is displayed after saving.

**Comment by duniang818** [comment]
no, the bug still exists in version 3.1.1.
how to fix the bug?
I made some changes to a chart, save and add to dashboard, but the changes not work, at some time, dont add the chart to the dashboard. 
somebody can fix this?

**Comment by rusackas** [comment]
Unable to replicate in 4.1. Closing.
