### ISSUE TITLE
Import of visualisations not working nor itself nor with dashboard

### ISSUE THREAD

**Issue by comdiv** [apache/superset#20737]
1. Create any visualisation
2. Export it to zip file
3. Remove previously created visualisation
4. Try to import visualization from zip file - it will write that all work well, but visualization not occured in visualization list!
5. Same with dashbord export import - dashbords and datasets are restored, but visualizations - not!

**Comment by andreabrumana** [comment]
Same issue

**Comment by AlessandroLollo** [comment]
Same issue here!

**Comment by comdiv** [comment]
Environment

1. Google Chrome 95.0.4638.69
2. master branch at  commit e60083b45b8953220e54c67544ce2381d7c96f2e
3. docker-compose -f docker-compose-non-dev.yml up -d
4. the only change in docker-compose file - switch postgres:10 to postgres:14 while it is in volume already after dev start
5. all other staff (python, node) comes from containers defined in docker-compose

**Comment by comdiv** [comment]
Not reproduced, think it was fixed some commits before

**Comment by stefanocascavilla** [comment]
@jacobcroope We are still experiencing the issue.
browser type and version: 103.0.5060.114
superset version: 2.0.0 (using docker image apache/superset:2.0.0)
any feature flags active: VERSIONE_EXPORT=True (by default in 2.0.0)

If we export a dashboard, and then delete the dashboard, charts, and dataset. If we then import the dashboard, the import completes successfully but all the charts are broken with the following error:

<img width="438" alt="Schermata 2022-07-19 alle 10 00 51" src="https://user-images.githubusercontent.com/19977405/179698854-7003ab51-7e75-4664-ad92-47508d8befba.png">

Notes: Dashboard filters, titles, and texts are correct.

**Comment by jacobcroope** [comment]
@stefanocascavilla Weird, I can't reproduce this on either of my installs or browsers. We regularly develop new charts and dashboards on our development system before exporting them to production which is what caught my interest in this error. I am guessing it has something to do with your particular configuration and I don't have a better idea than to maybe look at the logs on import to see what is erroring out. 

I do know that 1.3,1.5,2.0 all seem to be working for me on this behavior so maybe its time for a clean install?

**Comment by stefanocascavilla** [comment]
We were able to find the issue.
If we delete the broken charts, the correct ones appear (they were hidden on the right side of the dashboard pane).

**Comment by AlessandroLollo** [comment]
> We were able to find the issue. If we delete the broken charts, the correct ones appear (they were hidden on the right side of the dashboard pane).

To add a bit of context, this happens only with dashboards that were created with a Superset version < 2.0, in our case it was Superset 1.5.0

**Comment by erfanu25** [comment]
Facing same issue for
browser type and version: Google Chorme Version 105.0.5195.125 (Official Build) (64-bit)
superset version: 2.0.0
python version: Python 3.9.0
node.js version: v16.14.2
any feature flags active: No

**Comment by artemonsh** [comment]
I face the same issue trying to import charts from 1.4 to 2.0 or from 1.4 to 1.4
