### ISSUE TITLE
Snowflake-sqlalchemy connector no longer working.

### ISSUE THREAD

**Issue by nrav1360** [apache/superset#20863]
Previously, was able to connect the snowflake database to my superset instance. However, all of the charts I have (that used datasets from snowflake) now have errors that didn't exist before.

#### How to reproduce the bug

1. Install Superset via Docker. 
2. Add snowflake driver by adding snowflake-sqlalchemy<=1.2.4 to requirements-local.txt.
3. Connect to snowflake using credentials.
4. Attempt to create a chart using an imported dataset from snowflake.

### Expected results

A working chart.

### Actual results

Errors involving a missing NamedTuple.

#### Screenshots

<img width="679" alt="Screen Shot 2022-07-25 at 8 43 50 PM" src="https://user-images.githubusercontent.com/68169720/180918412-f16ff3e7-07ca-40d7-ae4e-d39030a74bed.png">

<img width="598" alt="Screen Shot 2022-07-25 at 8 44 15 PM" src="https://user-images.githubusercontent.com/68169720/180918448-83c0d26e-39f2-4827-b109-7a36da6a663f.png">

### Environment

- browser type and version: Safari 15.1
- superset version: 2.0.0
- python version: Python 3.10.4
- node.js version: v12.22.9
- any feature flags active: None

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [✔️ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [✔️ ] I have reproduced the issue with at least the latest released version of superset.
- [✔️ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by wiktor2200** [comment]
It exists on 1.5.0 and 1.5.1 as well. 
It seems to be external bug: https://github.com/snowflakedb/snowflake-connector-python/issues/1206

**Comment by wiktor2200** [comment]
I've fixed it.

The problem was caused by external source (releasing of `snowflake-connector-python` ver. `2.7.10` https://github.com/snowflakedb/snowflake-connector-python/releases today).

For Superset <-> Snowflake `snowflake-sqlalchemy 1.2.4` python package is used, which is quite old now (but it's only one version supported by Superset): https://superset.apache.org/docs/databases/snowflake/#snowflake and they are working on migration to new one.

Even having package version hardcoded: `snowflake-sqlalchemy==1.2.4` in helm definitions didn't help. Becuase `snowflake-sqlalchemy` package has requirements defined in python script here: `snowflake-connector-python<3.0.0`: https://github.com/snowflakedb/snowflake-sqlalchemy/blob/666843d320315d2fd2b5c4129b929af20669008d/setup.py#L36, so it's downloading the newest `2.7.10` version anyways (fulfilling the condiition `<3.0.0`), but this version is not compatible with `snowflake-sqlalchemy==1.2.4` and requires additional package: `typing-extensions>=4.3.0`.

So the fix here was to force install previous version of `snowflake-connector-python==2.7.9` (which still `<3.0.0`), as well as `typing-extensions>=4.3.0` so all requirements were fulfilled and `snowflake-sqlalchemy==1.2.4` doesn't download newest incompatible version.
```
typing-extensions>=4.3.0
snowflake-connector-python==2.7.9
snowflake-sqlalchemy==1.2.4
```

**Comment by EamonKeane** [comment]
Thanks a lot @wiktor2200 ! I struggled through this issue. It appears that it's been partially fixed in 2.7.11.

https://github.com/snowflakedb/snowflake-connector-python/issues/1206#issuecomment-1213487028

Like you mention, it looks like the pinning for typing-extensions could be relaxed since it appears to work above v4. This script works for me. Is there a more elegant/maintainable way of creating a production image?

```
#!/usr/bin/env bash
cd /tmp || exit
git clone https://github.com/apache/superset.git --branch=2.0.0
echo "snowflake-sqlalchemy==1.2.4" > superset/requirements/requirements-local.txt
cd superset || exit
# linux sed
sed -i 's/typing-extensions>=3.10, <4/typing-extensions>=4.3, <5/' setup.py
sed -i 's/typing-extensions==3.10.0.0/typing-extensions==4.3.0/' requirements/base.txt
docker build --tag apache-superset:2.0.0-dev --target dev .
```

**Comment by alldoami** [comment]
Can these reqs get considered? 
```
typing-extensions==4.3.0
snowflake-connector-python==2.7.9
snowflake-sqlalchemy==1.2.4
```

After pinning these packages, my errors went away but Superset is requiring a different version for `typing-extensions`. I think this is the only way this will work with the right version of the `snowflake` packages.

```
pkg_resources.DistributionNotFound: The 'typing-extensions<4,>=3.10' distribution was not found and is required by apache-superset
```

**Comment by wiktor2200** [comment]
Hello @alldoami! Finally I've also used requirements without: `typing-extensions`, when I posted my first reply it worked, but then I changed some other dependencies and I just used these two:
```
snowflake-connector-python==2.7.9
snowflake-sqlalchemy==1.2.4
```

@EamonKeane it's better idea to just create `Dockerfile` and extend your image (it's recommended in docs here: https://hub.docker.com/r/apache/superset) in section: `How to extend this image` so you just clone pre-build docker (master or specific version) and then extend it by running (or anything you need)
```
RUN pip install \
         snowflake-connector-python==2.7.9 \
         snowflake-sqlalchemy==1.2.4
```

**Comment by alldoami** [comment]
yup I've been using my own docker image!

**Comment by alldoami** [comment]
Hmm weird... I pinned just these two packages, but I am still getting 
```
│ superset-init-db pkg_resources.DistributionNotFound: The 'typing-extensions<4,>=3.10' distribution was not found and is required by apache-superset                            │
```

Which version of `typing-extensions` are you using @wiktor2200 ?

**Comment by alldoami** [comment]
This is my `Dockerfile`:
```
FROM apache/superset
USER root
RUN mkdir -p /home/superset
ENV PYTHONPATH=/home/superset:$PYTHONPATH
VOLUME /home/superset
RUN pip install psycopg2-binary==2.9.1
RUN pip install snowflake-sqlalchemy>=1.2.4
RUN pip install auth0-python==3.19.0
RUN pip install sqlalchemy-databricks>=0.2.0
RUN pip install snowflake-connector-python==2.7.9
RUN pip install snowflake-sqlalchemy==1.2.4
USER superset
```

**Comment by wiktor2200** [comment]
Maybe you should `pip install` everything with one `RUN` command, I'm running this one:
```
RUN rm -rf /var/lib/apt/lists/* && \
    pip install \
        Authlib==1.0.1 \
        flask-oidc==1.3.0 \
        psycopg2-binary==2.9.1 \
        snowflake-connector-python==2.7.9 \
        snowflake-sqlalchemy==1.2.4 \
        redis==3.5.3
```
Maybe there are some dependencies which are not fully covered. What is more, I've noticed that order of installing packages could matter.

**Comment by alldoami** [comment]
I reordered the packages and pinned `typing-extensions==3.10.0` but now get a `pyarrow` dependency problem, it looks like one of these packages is relying on `pyarrow==9.0.0` but superset requires `6.0.1`

**Comment by alldoami** [comment]
Looks like `sqlalchemy-databricks` had some higher `pyarrow` req, so this now works for me!
```
RUN pip install auth0-python==3.19.0
RUN pip install psycopg2-binary==2.9.1
RUN pip install snowflake-connector-python==2.7.9
RUN pip install snowflake-sqlalchemy==1.2.4
RUN pip install sqlalchemy-databricks==0.2.0
RUN pip install typing-extensions==3.10.0
RUN pip install databricks-sql-connector==2.0.2
RUN pip install pyarrow==6.0.1
```

**Comment by asemprini** [comment]
I don't know if it is strictly related, but when I follow the same steps above to add the snowflake connector in docker and attempt to test the connection in superset, I get the following error:

superset_app            | 2022-08-31 18:54:27,388:INFO:snowflake.connector.connection:Snowflake Connector for Python Version: 2.7.9, Python Version: 3.8.13, Platform: Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-glibc2.2.5
superset_app            | 2022-08-31 18:54:27,389:DEBUG:snowflake.connector.connection:connect
superset_app            | 2022-08-31 18:54:27,389:DEBUG:snowflake.connector.connection:__config
superset_app            | SupersetErrorsException
superset_app            | Traceback (most recent call last):
superset_app            |   File "/app/superset/databases/commands/test_connection.py", line 111, in run
superset_app            |     raise DBAPIError(None, None, None)
superset_app            | sqlalchemy.exc.DBAPIError: (builtins.NoneType) None
superset_app            | (Background on this error at: https://sqlalche.me/e/14/dbapi)
superset_app            |
superset_app            | The above exception was the direct cause of the following exception:
superset_app            |
superset_app            | Traceback (most recent call last):
superset_app            |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
superset_app            |     rv = self.dispatch_request()
superset_app            |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
superset_app            |     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
superset_app            |   File "/usr/local/lib/python3.8/site-packages/flask_appbuilder/security/decorators.py", line 89, in wraps
superset_app            |     return f(self, *args, **kwargs)
superset_app            |   File "/app/superset/views/base_api.py", line 113, in wraps
superset_app            |     raise ex
superset_app            |   File "/app/superset/views/base_api.py", line 110, in wraps
superset_app            |     duration, response = time_function(f, self, *args, **kwargs)
superset_app            |   File "/app/superset/utils/core.py", line 1549, in time_function
superset_app            |     response = func(*args, **kwargs)
superset_app            |   File "/app/superset/utils/log.py", line 244, in wrapper
superset_app            |     value = f(*args, **kwargs)
superset_app            |   File "/app/superset/views/base_api.py", line 83, in wraps
superset_app            |     return f(self, *args, **kwargs)
superset_app            |   File "/app/superset/databases/api.py", line 709, in test_connection
superset_app            |     TestConnectionDatabaseCommand(item).run()
superset_app            |   File "/app/superset/databases/commands/test_connection.py", line 136, in run
superset_app            |     raise DatabaseTestConnectionFailedError(errors) from ex
superset_app            | superset.databases.commands.exceptions.DatabaseTestConnectionFailedError: [SupersetError(message='(builtins.NoneType) None\n(Background on this error at: https://sqlalche.me/e/14/dbapi)', error_type=<SupersetErrorType.GENERIC_DB_ENGINE_ERROR: 'GENERIC_DB_ENGINE_ERROR'>, level=<ErrorLevel.ERROR: 'error'>, extra={'engine_name': 'Snowflake', 'issue_codes': [{'code': 1002, 'message': 'Issue 1002 - The database returned an unexpected error.'}]})]
superset_app            | 2022-08-31 18:54:27,407:WARNING:superset.views.base:SupersetErrorsException
superset_app            | Traceback (most recent call last):
superset_app            |   File "/app/superset/databases/commands/test_connection.py", line 111, in run
superset_app            |     raise DBAPIError(None, None, None)
superset_app            | sqlalchemy.exc.DBAPIError: (builtins.NoneType) None
superset_app            | (Background on this error at: https://sqlalche.me/e/14/dbapi)
superset_app            |
superset_app            | The above exception was the direct cause of the following exception:
superset_app            |
superset_app            | Traceback (most recent call last):
superset_app            |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
superset_app            |     rv = self.dispatch_request()
superset_app            |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
superset_app            |     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
superset_app            |   File "/usr/local/lib/python3.8/site-packages/flask_appbuilder/security/decorators.py", line 89, in wraps
superset_app            |     return f(self, *args, **kwargs)
superset_app            |   File "/app/superset/views/base_api.py", line 113, in wraps
superset_app            |     raise ex
superset_app            |   File "/app/superset/views/base_api.py", line 110, in wraps
superset_app            |     duration, response = time_function(f, self, *args, **kwargs)
superset_app            |   File "/app/superset/utils/core.py", line 1549, in time_function
superset_app            |     response = func(*args, **kwargs)
superset_app            |   File "/app/superset/utils/log.py", line 244, in wrapper
superset_app            |     value = f(*args, **kwargs)
superset_app            |   File "/app/superset/views/base_api.py", line 83, in wraps
superset_app            |     return f(self, *args, **kwargs)
superset_app            |   File "/app/superset/databases/api.py", line 709, in test_connection
superset_app            |     TestConnectionDatabaseCommand(item).run()
superset_app            |   File "/app/superset/databases/commands/test_connection.py", line 136, in run
superset_app            |     raise DatabaseTestConnectionFailedError(errors) from ex
superset_app            | superset.databases.commands.exceptions.DatabaseTestConnectionFailedError: [SupersetError(message='(builtins.NoneType) None\n(Background on this error at: https://sqlalche.me/e/14/dbapi)', error_type=<SupersetErrorType.GENERIC_DB_ENGINE_ERROR: 'GENERIC_DB_ENGINE_ERROR'>, level=<ErrorLevel.ERROR: 'error'>, extra={'engine_name': 'Snowflake', 'issue_codes': [{'code': 1002, 'message': 'Issue 1002 - The database returned an unexpected error.'}]})]
superset_app            | 172.19.0.1 - - [31/Aug/2022:18:54:27 +0000] "POST /api/v1/database/test_connection/ HTTP/1.1" 422 317 "http://localhost:8088/databaseview/list/?pageIndex=0&sortColumn=changed_on_delta_humanized&sortOrder=desc" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36"

**Comment by asemprini** [comment]
Just in case someone else finds this thread looking why snowflake connector is not working when installing with docker. I was getting this error:

`superset_app            | superset.databases.commands.exceptions.DatabaseTestConnectionFailedError: [SupersetError(message='(builtins.NoneType) None\n(Background on this error at: https://sqlalche.me/e/14/dbapi)', error_type=<SupersetErrorType.GENERIC_DB_ENGINE_ERROR: 'GENERIC_DB_ENGINE_ERROR'>, level=<ErrorLevel.ERROR: 'error'>, extra={'engine_name': 'Snowflake', 'issue_codes': [{'code': 1002, 'message': 'Issue 1002 - The database returned an unexpected error.'}]})]`

The problem was I was trying to use the following connection string: https://superset.apache.org/docs/databases/snowflake/

In the end, using the above libraries mentioned by @wiktor2200, I was able to make it work but selecting the snowflake data source and not using the above connection string. 
Also, another comment:
![image](https://user-images.githubusercontent.com/106770160/187770577-070f651d-4dda-42c6-9c91-8730767516cd.png)
The DATABASE NAME, is not e.g. xy12345.us-east-2.aws, it is the ACTUAL database name like "my_db". And the ACCOUNT below is where you put xy12345.us-east-2.

Just in case this might help someone else with a similar issue.

**Comment by ggmblr** [comment]
Hi,

we are running into the same issues as everyone else here. Same error code as @asemprini right now.

Currently we have the python packages that @wiktor2200 posted inside our ./docker/requirements-local.txt file. But still it doesn't connect.
Could someone that has a working connection explain in detail what files were changed and how.

Thanks in advance

**Comment by EamonKeane** [comment]
@ggmblr fwiw, this is what I have working, just extending the Dockerfile wasn't working for me. Putting this in a Makefile and then doing a docker build should work and lets you use the latest snowflkae-sqlalchemy version which has additional datatypes like Geography.

```
SHELL := /bin/bash
SUPERSET_COMMIT_HASH ?= c3f841713989634ef4ba522b6a89e04ff89e2c0d
SUPERSET_FOLDER ?= my_superset

.PHONY: superset
superset:
	rm -rf ${SUPERSET_FOLDER}
	git clone --single-branch https://github.com/apache/superset.git ${SUPERSET_FOLDER}
	cd ${SUPERSET_FOLDER} && \
	git checkout ${SUPERSET_COMMIT_HASH} && \
	echo "snowflake-sqlalchemy==1.4.1" > requirements/requirements-local.txt && \
	sed 's/typing-extensions>=3.10, <4/typing-extensions>=4.3, <5/' setup.py > /tmp/file.$$ && mv /tmp/file.$$ setup.py && \
	sed 's/typing-extensions==3.10.0.0/typing-extensions==4.3.0/' requirements/base.txt > /tmp/file.$$ && mv /tmp/file.$$ requirements/base.txt

```

**Comment by ggmblr** [comment]
Hey @EamonKeane , after running your makefile, which docker command do you execute?

Is it `docker-compose -f docker-compose-non-dev.yml up` ?

Also what are the changes in that commit that fixes the issues?

**Comment by EamonKeane** [comment]
@ggmblr 

```
.PHONY: build_image
build_image: superset
	@$(info docker version)
	@docker version
	@docker build -t superset-test --target dev ${SUPERSET_FOLDER}
```

**Comment by danbtl** [comment]
Quick note here for anyone trying to get Superset 2.0.1 running via docker-compose with the Snowflake connector:

Create a file `docker/requirements-local.txt` with the following content:
```
snowflake-connector-python==2.7.9
snowflake-sqlalchemy==1.2.4
```
Then restart the docker containers.

As mentioned by others here, it does not work out of the box with newer versions of `snowflake-sqlalchemy`.

**Comment by rusackas** [comment]
Sounds like this has all been resolved. If you're having similar problems in Superset 3.x, please open a new issue with updated context.
