### ISSUE TITLE
Embedded Dashboard 500 Error {{superser_domain}}/embedded/{{dashboard_id}}?uiConfig=1

### ISSUE THREAD

**Issue by progettoautomazione** [apache/superset#21146]
**Environment:**
Superset 2.0.0
Python 3.8
Server Web: Apache
OS: Ubuntu 22

Hi everyone, great job guys, keep going because the tool is cutting edge. Thanks. I'm having a trouble in embedding a dashboard:

I followed all under https://www.npmjs.com/package/@superset-ui/embedded-sdk and https://medium.com/@khushbu.adav/embedding-superset-dashboards-in-your-react-application-7f282e3dbd88

and I created this simple page: 
https://progestnow.com/superset.html

As you can see, auth appears going well, but the URL that gets generated gives 500 error: https://bi.progestnow.com/embedded/d4f94ba8-4737-42a4-913e-48e88829ae87?uiConfig=1

I checked the server logs and I found:
**AttributeError: 'LoginManager' object has no attribute 'reload_user'**
2022-08-22 10:38:52,595:INFO:werkzeug:92.53.59.220 - - [22/Aug/2022 10:38:52] "GET /embedded/d4f94ba8-4737-42a4-913e-48e88829ae87?uiConfig=1 HTTP/1.1" 500 -

Any idea why? Everything else on Superset looks great, I am not seeing any other 500 error that might led to misconfiguration of the tool. It's just this /embed/ route.

Thanks

**Comment by progettoautomazione** [comment]
My superset_config.py:

```
WEBDRIVER_BASEURL = "https://bi.progestnow.com/"

SUPERSET_FEATURE_EMBEDDED_SUPERSET = True

FEATURE_FLAGS = {
    "ENABLE_TEMPLATE_PROCESSING": True,
    "EMBEDDED_SUPERSET": True,
    "EMBEDDABLE_CHARTS": True,
}
DATA_CACHE_CONFIG = {
    "CACHE_TYPE": "SupersetMetastoreCache",
    "CACHE_KEY_PREFIX": "superset_results",  # make sure this string is unique to avoid collisions
    "CACHE_DEFAULT_TIMEOUT": 86400,  # 60 seconds * 60 minutes * 24 hours
}

HTTP_HEADERS = {'X-Frame-Options': 'ALLOWALL'}

SESSION_COOKIE_SAMESITE = None
ENABLE_PROXY_FIX = True
PUBLIC_ROLE_LIKE_GAMMA = True

ENABLE_CORS = True
CORS_OPTIONS = {
  'supports_credentials': True,
  'allow_headers': ['*'],
  'resources':['*'],
  'origins': ['*']
}

ENABLE_TIME_ROTATE = True
```

**Comment by mahesh-kockpit** [comment]
found any solution @progettoautomazione ?

**Comment by progettoautomazione** [comment]
> found any solution @progettoautomazione ?

sadly no, as a workaround, we are using simple iframe embed so far....

**Comment by cwegener** [comment]
@mahesh-kockpit @progettoautomazione This is caused by a later version of `flask-login` being pulled in as a dependency and Superset still calling the removed method. I don't know exactly which version of `flask-login` has removed the call, but I do know that `flask-login==0.4.1` is working fine

**Comment by mahesh-kockpit** [comment]
@cwegener thanks for your comment.  I tried this but same issue can you please help us how to implement embedded feature of superset.

**Comment by mahesh-kockpit** [comment]
Below is my browser console 
![image](https://user-images.githubusercontent.com/69502457/187129169-0c183e21-4c0d-46df-965f-a8314e909aa1.png)

Below is my IFrame screen shot which is empty
![image](https://user-images.githubusercontent.com/69502457/187129270-14131f29-b1e2-44ce-90ea-885d50616835.png)

**Comment by johntwyman** [comment]
I've encountered the same problem. Downgrading flask-login to 0.4.1 definitely fixed the problem for me.

[This OctoPrint issue](https://github.com/OctoPrint/OctoPrint/issues/3600) confirms @cwegener 's comment about the `flask-login` version. The [related PR](https://github.com/OctoPrint/OctoPrint/commit/55dafd511b2b69cde89848efbf4098c0bf696eb0) suggests the breaking change came with `flask-login:0.5`.

**Comment by userkdg** [comment]
up!

**Comment by Usiel** [comment]
Similar issue https://github.com/apache/superset/issues/21987, both should be fixed by https://github.com/apache/superset/pull/22462

**Comment by amarchilukuri** [comment]
Hi, we are also facing same issue. setting flask-login:0.4.1 or flask-login: 0.6.0 not resolved 
![exception500](https://user-images.githubusercontent.com/67103863/211979018-58e039a8-0d65-4536-9cdd-468ab0c7c14b.png)
the issue. We are using helm chart to setup superset in kubernetes. Someone please help to resolve the same.

We see AttributeError: LoginManager object has no attribute reload_user.

Attached the exception screenshot.

**Comment by Delfins** [comment]
Hi everyone, I understood that the issue has been recognised and probably fixed, but...where? I mean, I've the superset 2.0.0 version installed 7-8 months ago with a regoular pip install apache-superset
Now how do I get the fix?
Thanks

**Comment by Usiel** [comment]
> Hi everyone, I understood that the issue has been recognised and probably fixed, but...where? I mean, I've the superset 2.0.0 version installed 7-8 months ago with a regoular pip install apache-superset
Now how do I get the fix?
Thanks

I don't know which future release the fix will be included in @Delfins. In the meantime you can use the <a href="#issuecomment-1229623428">workaround</a> by @cwegener.

**Comment by Delfins** [comment]
> > Hi everyone, I understood that the issue has been recognised and probably fixed, but...where? I mean, I've the superset 2.0.0 version installed 7-8 months ago with a regoular pip install apache-superset
> > Now how do I get the fix?
> > Thanks
> 
> I don't know which future release the fix will be included in @Delfins. In the meantime you can use the [workaround](#issuecomment-1229623428) by @cwegener.

Thanks @Usiel but I'm a newbie of Python, how do I downgrade the flask version?

**Comment by Usiel** [comment]
Simplest way will be to adapt your pip install command to `pip install apache-superset==2.0.0 flask-login==0.4.1` or just `pip install flask-login==0.4.1` if you just want to fix your current setup (0.4.1 is perfectly compatible with Superset 2.0.0).

**Comment by rusackas** [comment]
This is likely fixed by now, and is pretty out of date if not. If people are still encountering this in currently suppored versions (3.x or newer) please open a new Issue with updated context, or a PR to address the problem.
