### ISSUE TITLE
Superset does not cast trino timestamp correctly

### ISSUE THREAD

**Issue by iercan** [apache/superset#21567]
I have upgraded `sqlalchemy-trino==0.4.1` to `trino==0.315.0` since sqlalchemy-trino deprecated . After that we started getting below error 

![image](https://user-images.githubusercontent.com/3406152/191951764-45212f14-a2f9-45f7-a366-91c6d514106e.png)

I did some investigation and realized superset started to set column type as `timestamp(3)` instead of `timestamp` after upgrade. This change prevent superset casts time correctly. I've compared queries and saw that superset does not cast time filter anymore. 

Casting before(working)
`inserted_at >= from_iso8601_timestamp('2022-09-16T09:07:45.000000')`

Casting after(erroneous)
`inserted_at >= '2022-09-16 08:47:13.000000'`

Clearly there is some compatibility issue with new trino client. For now I solved my problem by downgrading trino client but I'd appreciate If this issue solved so that we can use latest client 

#### How to reproduce the bug

1. Replace sqlalchemy-trino==0.4.1 with trino==0.315.0
2. Sync dataset(which have a timestamp column) columns 
3. Send a query with time filter.

### Environment

- superset version: 1.5.0 docker image

### Additional context

Related #16223

**Comment by mdesmet** [comment]
This issue is resolved in Superset 1.5.1.

See https://github.com/apache/superset/blob/48f3eb427300faf5aa0a5ba22b20997324df3d2d/superset/db_engine_specs/presto.py#L740-L762

Let me know if that works for you!

**Comment by iercan** [comment]
@mdesmet I've tested with 1.5.2. Looks like problem still exists.

Btw we are using mongo connector if it helps. 

![image](https://user-images.githubusercontent.com/3406152/194338696-59dc7f6a-9c8c-4153-8ffe-796219f0aedc.png)

**Comment by mdesmet** [comment]
I'm able to reproduce your issue. will post a PR later today.

**Comment by rusackas** [comment]
Seems like this should have been closed by the linked PR. Holler if there's any need to re-open.
