### ISSUE TITLE
Upgrading from 2.0.0 to 2.0.1rc2 causes an error when setting owner and roles on dashboard

### ISSUE THREAD

**Issue by ziggekatten** [apache/superset#21984]
1. Spin up an 2.0.0 Superset instalation in docker
2. Create Dashboard. 
3. Edit setting on dashboard and you are able to set owner, and roles on dashboard
4. Upgrade to 2.0.1rc2
5. Edit setting on dashboard

### Expected results

In owner and roles you should be able to select user / role

### Actual results

An error appears in drop down: Cannot read properties of undefined (reading 'active'). This happens both in Owner and Role

#### Screenshots

![image](https://user-images.githubusercontent.com/55629049/199117240-9f56fa7c-b5e6-47f6-9752-8ad8977b1c7d.png)
![image](https://user-images.githubusercontent.com/55629049/199117346-fd03f762-b3e3-4e95-8e26-e3259118385e.png)

### Environment

(please complete the following information):

- browser type and version: Chrome 106.0.5249.119
- superset version: `2.0.1` 
- python version: `3.8.12`
- node.js version: `node -v`
- any feature flags active: {"ALERT_REPORTS": True, "DASHBOARD_CROSS_FILTERS": True, "DASHBOARD_RBAC": True, "THUMBNAILS" : True, "THUMBNAILS_SQLA_LISTENERS": True, "ENABLE_TEMPLATE_PROCESSING": True, "ENABLE_TEMPLATE_REMOVE_
FILTERS": True, "ENABLE_SCHEDULED_EMAIL_REPORTS": True, "EMAIL_NOTIFICATIONS": True, "EMBEDDED_SUPERSET": True}

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by HetviTA** [comment]
We are also facing the same issue while adding owners to dashboards.

**Comment by shhhowtime** [comment]
Faced this error too. Found out that browser gets data for users and roles if you're clicking on the field. Also this happens only if you're editing dashboard properties.
![изображение_2022-11-17_103722784](https://user-images.githubusercontent.com/7834286/202348980-7d34dc96-91fa-43ca-ac5e-d7cf43bca292.png)

**Comment by xmnlab** [comment]
just for the record, I tried this migration some weeks ago .. and the entire application (frontend) wasn't work
maybe it was something about custom html pages or maybe some configurations .. or something in the structure of package is different than the previous one .. and my own conda package (based on the conda-forge version) for that was not working properly

**Comment by oleg-savko** [comment]
also have the same issue

**Comment by rusackas** [comment]
Is this still an issue with the newer 2.0.1 release candidates? rc4 is up for testing, and rc5 is en route.

**Comment by mattrei** [comment]
yes still open. on my instance I get this error message in the newest rc5
<img width="663" alt="image" src="https://user-images.githubusercontent.com/379706/206848507-001f30f9-d17c-45a6-9b51-5e6de57d26d0.png">

**Comment by rusackas** [comment]
CC @eschutho @AAfghahi

**Comment by rusackas** [comment]
I think @eric-briscoe is hot on the trail of this one.

**Comment by eschutho** [comment]
This should be fixed for 2.0.1. Closing the issue, but feel to reopen if you find it again while testing.

**Comment by DiogoReisPinto** [comment]
The error is gone now with 2.0.1-rc6 but we are still unable to change the dashboard ownership. If we try to save the changes nothing happens. I've checked the backend logs and looks like we are getting a 400 error on the API call to update the dashboard:

`[16/Dec/2022:11:07:08 +0000] "PUT /api/v1/dashboard/6 HTTP/1.1" 400 75 "https://<ENDPOINT_REDACTED>/dashboard/list/?pageIndex=0&sortColumn=changed_on_delta_humanized&sortOrder=desc&viewMode=table" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"`

**Comment by ziggekatten** [comment]
2.0.1rc6 seems to fix this. Saving owner and roles does work in my test environment.

**Comment by oleg-savko** [comment]
Unfortunatelly, after upgrade superset to 2.0.1, it still cant update owners for dashboard:(

![Screenshot 2022-12-26 at 12 57 56](https://user-images.githubusercontent.com/14272376/209535245-32b4f1d1-b41b-4b9e-ae7a-2095127c912f.png)

**Comment by eschutho** [comment]
Yeah, we'll take another look. Thanks for reporting. cc @eric-briscoe

**Comment by sfirke** [comment]
FYI I can't replicate this bug in 2.0.1, I can add/remove owners and roles on both existing (from 2.0.0) and new dashboards.

**Comment by mdeshmu** [comment]
@eschutho is this issue fully resolved. Is it safe to upgrade to 2.0.1 with dashboard_rbac enabled?

**Comment by eschutho** [comment]
@mdeshmu Does this issue only happen when you have dashboard_rbac enabled?
