### ISSUE TITLE
Users who are not in the Admin role cannot edit any dashboards

### ISSUE THREAD

**Issue by TinTin-DXQ** [apache/superset#24234]
Users who are not in the Admin(Default Admin) role cannot edit any dashboards, even if the role I created is just to copy the Admin role and the dashboard is created by the user.

#### How to reproduce the bug

1. Go to 'List Roles'
2. Click on 'Admin-Copy Role-Edit Admin copy-Add a User to the Admin copy Role' 
3. Switch user, use this new user login superset
4. Create a new dashboard
5. Create a new chart (steps are not described in detail) and add to the dashboard
6. Go to the dashboard
7. See error: the user who created the dashboard cannot edit it

### Expected results
the user who created the dashboard can edit it
<img width="1277" alt="image" src="https://github.com/apache/superset/assets/34983295/aee53fbb-fb3b-4d2a-961e-da9278f1e017">

### Actual results
the user who created the dashboard cannot edit it
<img width="1277" alt="image" src="https://github.com/apache/superset/assets/34983295/370c26c1-2ed1-4c6e-bde0-02aa7a3af8db">

### Environment

use docker-compose-non-dev.yml create the docker container, just change the file docker/pythonpath_dev/superset_config.py
`FEATURE_FLAGS = {"ALERT_REPORTS": True, "DRILL_TO_DETAIL": True, "DRILL_BY": True}`

- browser type and version: chrome Version 113.0.5672.127(x64)
- superset version: `master`
- python version: `Python 3.9.16`
- node.js version: `none` 
- any feature flags active: 

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by roks531** [comment]
Same issue here, is this being addressed, or are there any solutions?

**Comment by roks531** [comment]
Upgraded to version 2.1.0-dev and the problem is gone, as it seams this must have been a bug which is resolved in later versions. So now when one is the owner, he can also edit the dashboard without being in the Admin role.

**Comment by rusackas** [comment]
Seems like this is likely fixed, and is pretty out of date if not. If people are still encountering this in current versions (3.x) please open a new Issue or a PR to address the problem.
