### ISSUE TITLE
Wrong extension for email report attachment when server pagination

### ISSUE THREAD

**Issue by Regonos** [apache/superset#32858]
### Steps to reproduce
1. Create table chart
2. Enable server pagination
3. Create email report
4. Set Content Format to "Send as CSV"

### Actual Result
Getting an email with "csv" attachment but file is really a "zip". 

### Expected Result
Attachment should have "zip" extension.

### Potential cause
It is because server pagination executes two queries, and results is downloaded as zip file.

### Screenshots/recordings

![Image](https://github.com/user-attachments/assets/31206da6-92ad-4c35-8bb0-9bbbdcdb55f1)
![Image](https://github.com/user-attachments/assets/0b689a8e-c060-4ee8-bc18-974fb591d64e)
![Image](https://github.com/user-attachments/assets/9e2c7637-17dc-434b-ada9-62a12f3c5713)
![Image](https://github.com/user-attachments/assets/17e857d6-0bbc-4e47-b3c6-c9ffbc5136f0)

### Superset version

4.1.2

### Python version

3.9

### Node version

16

### Browser

Firefox

### Checklist

- [x] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [x] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [x] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by rusackas** [comment]
Seems to be a duplicate of https://github.com/apache/superset/issues/25647?

**Comment by rusackas** [comment]
I think this one is resolved... at least I tried to reproduce it on the other thread and couldn't. Can anyone check on latest `master`?

**Comment by dwoods-unimax** [comment]
I believe I still see this issue in version 5 of Superset. I have a chart that issues two queries and when exporting as a CSV for a scheduled report I get a file with a CSV extension but appears to really be an uncompressed ZIP file.

**Comment by dwoods-unimax** [comment]
FYI - I'm still seeing this behavior in version 6 rc4.

**Comment by rusackas** [comment]
Thanks for confirming @dwoods-unimax, still live on 6.0 then. The attachment is really a zip but gets a `.csv` suffix when multiple queries bundle, so the fix is naming it `.zip` on that path.

**Comment by endimonan** [comment]
Hi @rusackas, is it ok if I work on that?

My plan is to keep .csv for regular CSV content and use .zip only if the attachment payload is zip. Something like that, I will investigate a bit.

EDIT: I will open a PR shortly 👍
