### ISSUE TITLE
Embedded dashboard cannot support dataset macro in sql template

### ISSUE THREAD

**Issue by shirley26107plus** [apache/superset#32894]
### Bug description

I used a dataset macro in dataset sql with jinja template

<img width="1344" alt="Image" src="https://github.com/user-attachments/assets/3bca47c5-3c70-43d9-9afd-467363ed3906" />

`select team_manager from {{ dataset(66) }}
`

And the dashboard works fine

![Image](https://github.com/user-attachments/assets/c078e9f1-fc17-4624-8def-2fbccab6c76f)

But when I embedded it into frame with sdk, I got an error like this:

![Image](https://github.com/user-attachments/assets/7d0e7667-1c5c-409a-a642-1f89efb18bda)

### Superset version

master / latest-dev

### Python version

3.9

### Node version

16

### Browser

Chrome

### Checklist

- [x] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [x] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [ ] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by rusackas** [comment]
Is this still happening on current `master`? Wondering if anything changed after the SQLGlot migration.

**Comment by ikstewa** [comment]
We run into the same issue when using the `metric()` macro with an embed. I believe it fails for the same reason that it is trying to do a dataset lookup, even if the dataset is the one the macro is being ran from:

https://github.com/apache/superset/blob/05c6a1bf200a916ce152b669735d8fd53a8b87aa/superset/jinja_context.py#L1067-L1109

**Comment by Vitor-Avila** [comment]
Fixed with https://github.com/apache/superset/pull/35508

**Comment by tal952** [comment]
This is still happening, the https://github.com/apache/superset/pull/35508 only fixed the metric_macro, not dataset_macro. I'm not familiar enough with superset, is it the same fix?
