### ISSUE TITLE
[6.0.0rc2]Configure URL_PREFIX, I get an error when clicking the download Excel function on the Table chart

### ISSUE THREAD

**Issue by XiaochuRiver** [apache/superset#35883]
### Bug description

<img width="2516" height="648" alt="Image" src="https://github.com/user-attachments/assets/fbaf3b92-adaa-4ff8-b6f7-25cebab64131" />

When I click this button, the URL_PREFIX will appear twice. For example, if I configure SUPERSET_APP_ROOT = '/ana', the download URL will contain two /ana/ana/data entries, and then the interface will display a connection loss error message.

### Superset version

master / latest-dev

### Python version

3.11

### Node version

16

### Browser

Chrome

### Checklist

- [x] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [x] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [x] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by rusackas** [comment]
Probably fixed by `https://github.com/apache/superset/pull/35118` which just merged. Can you check on `master`?

**Comment by khiem2794** [comment]
the bug is still there, app root got appended in both places causing duplication @rusackas

https://github.com/apache/superset/blob/983b633972fde332921f63f28d04f8975f14459f/superset-frontend/src/explore/exploreUtils/index.ts#L360

https://github.com/apache/superset/blob/983b633972fde332921f63f28d04f8975f14459f/superset-frontend/packages/superset-ui-core/src/connection/SupersetClientClass.ts#L126

Currently, my workaround is to use additional middleware to redirect to the right path when exporting csv
